server {
  listen 8080;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;
  
  # Proper MIME types
  location ~* \.js$ {
    types { application/javascript js; }
    add_header Cache-Control "no-cache, must-revalidate";
  }
  
  location / {
    try_files $uri $uri/ /index.html;
  }
  
  gzip on;
  gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
  gzip_min_length 1000;
}
